# This workflow validates, deploys, and runs the specified bundle
# within a production target named "prod".
name: christoph_test

on:
   workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install python-semantic-release
        run: |
          pip install python-semantic-release

      - name: Generate changelog
        run: semantic-release changelog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "luo14938@gmail.com"
          git add CHANGELOG.md
          git commit -m "Update changelog [skip ci]" || echo "Nothing to commit"
          git push origin main