name: Merge 'main' to 'development' 

on:
  workflow_run:
    workflows: ["Merge 'main' to 'development'", "Release","Major Release on releases/* branches"]
    branches:
      - 'main'
      
jobs:
  merge:
    runs-on: ubuntu-22.04
    steps:
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'main'   
          target: 'development'
