# This workflow validates, deploys, and runs the specified bundle
# within a production target named "prod".
name: "Test deployment"
 
# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1
 
# Trigger this workflow whenever a pull request is pushed to the repo's
# main branch.
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: List files after checkout
      run: ls -la
      
    - name: Databricks Asset Bundles Deploy
      uses: lumiastudios/Databricks-Asset-Bundles-Deploy@v1.0.0
      with:
        # The directory containing the Databricks asset bundle configuration
        working-directory: .
        # The Databricks workspace host URL
        databricks-host: https://adb-2474944416409806.6.azuredatabricks.net/?o=2474944416409806
        # The target environment for the Databricks asset bundle deployment
        databricks-bundle-env: dev
        # The type of authentication to use (token or oauth)
        authentication-type: oauth
        # Databricks personal access token for authentication
        databricks-client-secret: ${{secrets.DATABRICKS_TOKEN }}
        # Databricks OAuth client ID for authentication
        databricks-client-id: ${{secrets.CLIENT_ID }}

       
           
