name: Major Release on New Branch

on:
  create:
    branches:
      - 'releases/**'

jobs:
  major-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
    
      - name: Install Dependencies
        run: pip install python-semantic-release

      - name: Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          git_committer_name: "GitHub Actions"
          git_committer_email: "luo14938@gmail.com"
          github_token: ${{ secrets.GH_TOKEN }}
          force: "major" 
