name: Major Release on releases/* branches 

on:
  push:
    branches:
      - 'releases/**'
      
jobs:
  release:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: print step output
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: print GITHUB_HEAD_REF
        run: echo "${GITHUB_HEAD_REF}"
        
      - name: print GITHUB_REF
        run: echo "${GITHUB_REF}"
      - name: Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          git_committer_name: "GitHub Actions"
          git_committer_email: "luo14938@gmail.com"
          github_token: ${{ secrets.GH_TOKEN }}
          force: "major" 

      - name: Check Release
        run: |
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Tag: ${{ steps.release.outputs.tag }}"
          echo "Released: ${{ steps.release.outputs.released }}"

          if [ "${{ steps.release.outputs.released }}" == "false" ]; then
            echo "No release created"
            exit 1
          fi
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: ${{ steps.extract_branch.outputs.branch }}
          target: 'main'
