name: Major Release on New Branch

on:
  create:
    branches:
      - "release/*"

jobs:
  major-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install python-semantic-release

      - name: Release New Major Version
        if: env.from_main == 'true'
        run: semantic-release publish --major
